-- Machine-readable error codes returned to the browser inside the
-- FetchBridge response envelope. Add new codes here, never inline.

ErrorCodes = {
    INVALID_REQUEST = "INVALID_REQUEST",
    INVALID_ARGUMENTS = "INVALID_ARGUMENTS",
    INVALID_LOGIN = "INVALID_LOGIN",
    INVALID_EMAIL = "INVALID_EMAIL",
    INVALID_PASSWORD = "INVALID_PASSWORD",
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
    NOT_AUTHENTICATED = "NOT_AUTHENTICATED",
    ACCOUNT_BANNED = "ACCOUNT_BANNED",
    ACCOUNT_NOT_FOUND = "ACCOUNT_NOT_FOUND",
    ACCOUNT_ALREADY_EXISTS = "ACCOUNT_ALREADY_EXISTS",
    RATE_LIMITED = "RATE_LIMITED",
    REQUEST_TIMEOUT = "REQUEST_TIMEOUT",
    INTERNAL_ERROR = "INTERNAL_ERROR",
    RESOURCE_UNAVAILABLE = "RESOURCE_UNAVAILABLE",
    UNKNOWN_ENDPOINT = "UNKNOWN_ENDPOINT",
    INVALID_SPAWN = "INVALID_SPAWN",
    FORBIDDEN = "FORBIDDEN",
    REPORT_NOT_FOUND = "REPORT_NOT_FOUND",
    PLAYER_NOT_FOUND = "PLAYER_NOT_FOUND",
}
